### ISSUE TITLE
How to install openCV on Maix-II

### ISSUE THREAD

**Issue by diazGT94** [sipeed/MaixPy3#12]
Hello I would like to use openCV for testing some Haar Classifiers and for extracting some frames of a video for analyze them. I tried to install opencv with PIP but it gaves me the following error: ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device

Then I install it using opkg and it's installed. However, when I tried to import it througs an error. Is there a chance to use Open-CV on this board?

![imagen](https://user-images.githubusercontent.com/77060595/115454730-c8229300-a229-11eb-86be-13a581def772.png)

**Comment by junhuanchen** [comment]
MAIXII currently has OpenCV without Python-OpenCV

**Comment by diazGT94** [comment]
Why can't it be used with Python? It means I can only using with C++?

**Comment by junhuanchen** [comment]
It's not there yet

**Comment by thepian** [comment]
I think in general it would be good to have instructions on how to expand the OS disk on the SD card. It's annoying to have 90% free on a 16Gb card, but be out of space due to the partition layout.

**Comment by irfan798** [comment]
I made a builder for opencv-python for Maix-II Dock

You can download binary package from here:
https://github.com/irfan798/maix3_opencv_python/releases/tag/cv-4.5.5.62_numpy-1.19.2

I'm not sure if its 100% optimized though
