### ISSUE TITLE
关于在Maix 2 Dock上播放视频的方案

### ISSUE THREAD

**Issue by silentobservers** [sipeed/MaixPy3#18]
想问，能不能播放本地MP4文件，实现思路是怎么样的？
我找到了一个video_stream好像是播放mjpeg的？但我下的视频demo报错，错误如下
 frame_length = int(frame_length.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
----------------------------------------------------------------------------------------------
官方大大和热心网友帮个忙，求助一个便捷的播放本地视频的方法，感谢感谢

**Comment by Neutree** [comment]
没有硬件解码器, 都是软件的, 找找通用的软件就好了

**Comment by junhuanchen** [comment]
已经在新的镜像里放入了 ffmpeg 了
