### ISSUE TITLE
保存图片显示出来的颜色不对

### ISSUE THREAD

**Issue by xl736592857** [sipeed/MaixPy3#21]
代码如下:![1627963508](https://user-images.githubusercontent.com/6007025/127956165-78516fa0-dfe8-4f57-a08f-5786b87ae407.jpg)`from PIL import Image, ImageFont, ImageDraw
from maix import display, camera
import time
img = camera.capture()
img.save('/mnt/UDISK/%d.jpg' % int(time.time()), quality=100)`

**Comment by junhuanchen** [comment]
等一下 0.3.1 的更新 https://github.com/sipeed/MaixPy3_scripts

**Comment by junhuanchen** [comment]
这种情况多数是上电启动的时候，ISP 还没打开导致的。
