### ISSUE TITLE
requests或者mqtt库无法脱机运行

### ISSUE THREAD

**Issue by Ghost1989** [sipeed/MaixPy3#38]
在maxipy0.5上，如果连接Jupyter可以正常使用requests或者mqtt库，但是脱机之后在main.py里相同的代码就无法运行，即使这会使用充电宝供电也不行，使用手机2.4G热点也不可以
![image](https://user-images.githubusercontent.com/17744915/175223258-550680ac-0181-46b4-9c53-5b2bd1e224a8.png)

import requests
from maix import display, image
r = requests.get('https://api.github.com/user', auth=('user', 'pass'))

hello_img = image.Image().new(size = (240, 240), color = (255, 0, 0), mode = "RGB")     #创建一张红色背景图
hello_img.draw_string(30, 115, str(r.status_code), scale = 1.0,color = (255, 255, 255), thickness = 1) #在红色背景图上写下hello world
display.show(hello_img)

**Comment by junhuanchen** [comment]
[How to ask questions?（如何提问？）](https://github.com/sipeed/MaixPy3/issues/5)

**Comment by Ghost1989** [comment]
在v831的maxipy0.5版本，无法自动运行main.py里的requests请求，但相同代码在jupyter连接时却是可以运行的

**Comment by junhuanchen** [comment]
在遇到问题之前，请浏览一下（项目、社区）是否有相关的问题反馈记录，再把你遇到的问题，操作，环境，现象都写下来。

遇到了什么问题？
你做了什么操作？要有截图或代码！
你在什么系统环境下进行的操作？
期望的现象与实际的现象有什么不符？（有图有真相！）
