### ISSUE TITLE
Fail download face model from maixhub

### ISSUE THREAD

**Issue by ricardojlrufino** [sipeed/MaixPy3#40]
Download error 
![image](https://user-images.githubusercontent.com/515675/177240005-4fb278e3-cdc5-413b-9f08-a769f174a85b.png)

Can someone send me this model?

**Comment by junhuanchen** [comment]
In fact, in the latest systems, this model is built in. (retinaface.py)

**Comment by wonderfullook** [comment]
Maybe you can try `python /root/retinaface.py` to run this model in the linux shell on v831

**Comment by ricardojlrufino** [comment]
retinaface.py works thanks

**Comment by ricardojlrufino** [comment]
There is some documentation that explains these parameters ?
core_threshold = 70                            #识别分数阈值
input_size = (224, 224, 3)                      #输入图片尺寸
input_size_fe = (128, 128, 3)                   #输入人脸数据
feature_len = 256                               #人脸数据宽度
steps = [8, 16, 32]                             #

**Comment by ricardojlrufino** [comment]
I managed to run on another device:
![TEST_FACEDETECT_01_PC1](https://user-images.githubusercontent.com/515675/177903096-70b273d3-7030-452a-b0fc-4b155e7f2724.PNG)

https://user-images.githubusercontent.com/515675/177903100-0daa39b1-04e0-452b-b8d7-886673622fd4.mp4

**Comment by Neutree** [comment]
core_threshold = 70 #  threshold, when score > this value, we think it's the pepole
input_size = (224, 224, 3) #model input shape
input_size_fe = (128, 128, 3) # face feature mode input size
feature_len = 256 # face feature array length
steps = [8, 16, 32] # model params, just fixed to this value
