### ISSUE TITLE
Maix 2 Dock 点亮后一直显示logo、

### ISSUE THREAD

**Issue by AdamZhang0425** [sipeed/MaixPy3#8]

**Comment by AdamZhang0425** [comment]
按照实例安装镜像成功点亮后，运行camera Capture 代码：

from maix import display, camera
display.show(camera.capture())

运行后如图所示
![image](https://user-images.githubusercontent.com/45141527/111873490-6d4c1080-89cb-11eb-868c-e901bda4cd42.png)
但LCD仍显示开机Logo，无画面输出

**Comment by anku2424** [comment]
@AdamZhang0425 您是如何解决这个问题的

**Comment by Neutree** [comment]
按键推出开机程序

或者执行`top `看一下开机画面的进程, `kill -9 进程PID`杀掉进程, 然后再执行, 这个开机任务在`/etc/init.d/rc.final`末尾, 删除也可
